[CHE-20] Add LeaderBoard page
27-mf-05/cheburland pull request #11
Opened 2023-06-30 11:55 UTC by mironovsergey

Добавлена верстка страницы Лидерборд

В данный момент в таблице лидеров выводятся захардкоженные данные. Впоследствии эти данные должны быть получены с бэка. Также нужно будет переписать функцию сортировки.

2023-06-30 12:12 UTC, aaa15test commented
мы создаем пр в ветку develop, а не main

2023-06-30 13:01 UTC, HelenaSuslenkova requested changes

2023-06-30 13:01 UTC, HelenaSuslenkova commented on packages/client/src/pages/leader-board/LeaderBoard.tsx
> +  ])
Все данные мы будем хранить в  context. Поэтому стейт здесь не нужен

Вместо стейта сделай простой объект с тестовыми данными

2023-06-30 13:01 UTC, HelenaSuslenkova commented on packages/client/src/pages/leader-board/LeaderBoard.tsx
> +  )
Этот функционал здесь лишний,  так как в таблице выводится имя пользователя и максимальное количество баллов. Данные уже будут выводиться в отсортированном виде по убыванию количества баллов
В дальнейшем когда понадобится сортировка можно использовать `mantine-datatable`, там уже все есть для сортировки

2023-06-30 13:17 UTC, HelenaSuslenkova requested changes

2023-06-30 13:17 UTC, HelenaSuslenkova commented on packages/client/src/pages/leader-board/LeaderBoardTable.tsx
> +          <th style={{ width: '1%' }}>
w={"1%"}

2023-06-30 13:17 UTC, HelenaSuslenkova commented on packages/client/src/pages/leader-board/LeaderBoardTable.tsx
> +          <th style={{ width: '1%' }}></th>
w={"1%"}

2023-06-30 13:31 UTC, aaa15test commented on packages/client/src/pages/leader-board/LeaderBoardTable.tsx
> +              uppercase>
(это больше рекомендация) перемести угловую скобку > на новую строку. так код легче читается и сразу понятно, где закончился список пропсов компонента

2023-07-02 13:36 UTC, HelenaSuslenkova requested changes

2023-07-02 13:36 UTC, HelenaSuslenkova commented on packages/client/src/pages/leader-board/LeaderBoardTable.tsx
Нужно поместить этот компонент в src/pages/leader-board/components/ ,  так как это компонент, который мы используем на странице LeaderBoard

2023-07-02 13:36 UTC, HelenaSuslenkova commented on packages/client/src/components/back-button/BackButton.tsx
Этот компонент не нужен

2023-07-02 13:36 UTC, HelenaSuslenkova commented on packages/client/src/pages/leader-board/LeaderBoard.tsx
> +        <BackButton />
Вместо  `<BackButton />` :

```
<Button component={Link} to={'/'} variant="default">
     {`< Главная`}
 </Button>
```

2023-07-02 15:02 UTC, HelenaSuslenkova approved these changes

2023-07-02 15:04 UTC, merged