[CHE-19] Add registration page and validation
27-mf-05/cheburland pull request #14
Opened 2023-06-30 12:37 UTC by GeorgyPasyuk

Добавил страницу регистрации и валидацию

2023-06-30 13:16 UTC, HelenaSuslenkova requested changes

2023-06-30 13:16 UTC, HelenaSuslenkova commented on packages/client/src/pages/main/constants.ts
> +}
Validation здесь нужно убрать,  так как 
1) packages/client/src/pages/main/constants.ts - здесь мы пишем константы только для страницы Main
2) валидацию лучше добавим в рамках отдельной задачи (она у тебя CHE-18) =)

2023-06-30 13:16 UTC, HelenaSuslenkova commented on packages/client/src/pages/registration/Registration.tsx
> +    },
пока убери, сделаем валидацию в рамках CHE-18

2023-06-30 13:27 UTC, aaa15test commented on packages/client/src/pages/registration/Registration.tsx
> +          py="50px">
(это больше рекомендация) перемести угловую скобку `>` на новую строку. так код легче читается и сразу понятно, где закончился список пропсов компонента

2023-06-30 13:33 UTC, HelenaSuslenkova requested changes

2023-06-30 13:33 UTC, HelenaSuslenkova commented on packages/client/src/pages/registration/Registration.tsx
> +    <Box id="mainPage" m="-16px">
Box тут лишний

2023-06-30 13:33 UTC, HelenaSuslenkova commented on packages/client/src/pages/registration/Registration.tsx
> +      <Flex align="center" justify="center" h="100vh">
h="100vh" - это не нужно

2023-06-30 13:33 UTC, HelenaSuslenkova commented on packages/client/src/pages/registration/Registration.tsx
> +}))
`createStyles` не используем, стилизуем только через атрибуты компонентов

2023-07-02 11:38 UTC, HelenaSuslenkova requested changes

2023-07-02 11:38 UTC, HelenaSuslenkova commented on packages/client/src/pages/registration/Registration.tsx
> +          <Button mb="2rem" fullWidth={true} variant="default" type="submit">
variant="default" убери

2023-07-02 11:38 UTC, HelenaSuslenkova commented on packages/client/src/pages/registration/Registration.tsx
> +          </Text>
сделай с помощью компонента `NavLink`

2023-07-02 12:55 UTC, HelenaSuslenkova approved these changes

2023-07-02 12:59 UTC, merged