[CHE 24] Add game over screen
27-mf-05/cheburland pull request #18
Opened 2023-07-01 11:29 UTC by aaa15test

Добавлена верстка экрана завершения игры

<img width="547" alt="Снимок экрана 2023-07-01 в 14 26 24" src="https://github.com/27-mf-05/cheburland/assets/91631529/535f860d-2208-4852-a91c-3d26419d4f05">

2023-07-01 11:48 UTC, HelenaSuslenkova requested changes

2023-07-01 11:48 UTC, HelenaSuslenkova commented on packages/client/src/components/gameOverScreenModal/GameOverScreenModal.tsx
> +    </Modal>
У нас будет несколько модалок. Поэтому нужно. сделать универсальный компонент, который принимает контент (содержимое модального окна) и оборачивает его в `Мodal`

2023-07-02 09:26 UTC, HelenaSuslenkova requested changes
создай папку `features` внутри `src` и помести туда компонент `GameOver`.  В `features` у нас буду сборные компоненты, которые не будут универсальными

2023-07-02 09:26 UTC, HelenaSuslenkova commented on packages/client/src/components/gameOverScreenModal/GameOverScreenModal.tsx
Думаю лучше назвать компонент проще `GameOver`

2023-07-02 09:26 UTC, HelenaSuslenkova commented on packages/client/src/components/gameOverScreenModal/GameOverScreenModal.tsx
> +  const [opened, { close }] = useDisclosure(isOpenned)
Это нужно перенести в `ModalWrapper`, так как этот хук относится к компоненту `Modal`, а не к его контенту

2023-07-02 09:26 UTC, HelenaSuslenkova commented on packages/client/src/components/gameOverScreenModal/GameOverScreenModal.tsx
> +      close={close}>
`close` - убери,  `openned` оставь в качестве пропса, так как потребуется менеджерить открытие окна из внешнего кода

2023-07-05 14:50 UTC, mironovsergey requested changes

2023-07-05 14:50 UTC, mironovsergey commented on packages/client/src/features/gameOver/GameOver.tsx
> +}
Меня немного смущает, что функция для обновления состояния `setOpened` передается в качестве пропса в компонент `ModalWrapper`, а в самом компоненте `setOpened` типизирована как `any`. Было бы лучше создать дополнительную функцию `handleClose`  в компоненте `GameOver`, которая вызывала бы `setOpened`, и передавать в качестве пропса именно ее. Заодно можно явно типизировать переменную состояния.

```
const [opened, setOpened] = useState<boolean>(isOpened)

const handleClose = () => {
  setOpened(false)
}

return (
  <ModalWrapper
    // ...
    onClose={handleClose}>
    { /*  ... */ }
  </ModalWrapper>
)
```

Проп `onClose` являлся бы простой функцией, и компонент `ModalWrapper` был бы более универсальным, так как в него можно было бы передать любую функцию, а не только функцию состояния.

Но, по моему этот функционал здесь избыточен. Здесь достаточно просто передавать проп `isOpened` в компонент `ModalWrapper`, а в нем уже используется хук `useDisclosure`, который предоставляет функцию закрытия модалки. То есть в компоненте `GameOver` вообще не нужно состояние. Обработчики клика на кнопках нам не нужны, так как эти кнопки делают переход на другие страницы.

2023-07-05 17:06 UTC, dksr approved these changes

2023-07-06 09:23 UTC, closed without merging