[CHE-22] Profile page
27-mf-05/cheburland pull request #24
Opened 2023-07-03 16:02 UTC by HelenaSuslenkova

Добавлена страница профиля
Настроила axios
Настроила  react-query 
Добавила обертки для запросов

2023-07-03 19:33 UTC, GeorgyPasyuk approved these changes

2023-07-03 19:50 UTC, aaa15test commented on packages/client/src/components/image-form/ImageForm.tsx
> +type AvatarFormProps = {
если компонент называется `ImageForm `, то может и тут стоит заменить на `ImageFormProps`

или, если мы в дальнейшем будем использовать этот компонент только для смены аватара юзера, то стоит везде поменять `ImageForm ` на `AvatarForm `

2023-07-04 13:48 UTC, mironovsergey commented on packages/client/src/app/api/axios.ts
> +export const client = axios.create({
Зачем здесь экспорт, если есть дефолтный экспорт

2023-07-04 13:49 UTC, mironovsergey commented on packages/client/src/app/api/axios.ts
> +const API_BASE_URL = `https://ya-praktikum.tech/api`
Лучше использовать одинарные кавычки

2023-07-04 13:50 UTC, mironovsergey commented on packages/client/src/app/api/axios.ts
> +  response => {
Можно указать тип response
`(response: AxiosResponse)`

2023-07-04 13:52 UTC, mironovsergey commented on packages/client/src/app/api/request.ts
> +  const onSuccess = function S(response: AxiosResponse) {
Здесь можно явно указать тип возвращаемого значения
`const onSuccess = function S(response: AxiosResponse<T>): T`

2023-07-04 13:54 UTC, mironovsergey commented on packages/client/src/app/api/services/user.service.ts
> +    newPassword: 'string'
Здесь не нужны кавычки
`{ oldPassword: string; newPassword: string }`

2023-07-04 13:54 UTC, mironovsergey commented on packages/client/src/app/api/services/user.service.ts
> +  static search = (data: { login: 'string' }) => {
Здесь не нужны кавычки
`{ login: string }`

2023-07-04 13:56 UTC, mironovsergey commented on packages/client/src/hooks/useAvatar.ts
> +    avatar(formData)
Константа `file` может иметь значение `undefined`. Нужно добавить проверку:
`
if (file) {
  const formData = new FormData()
  formData.append('avatar', file as Blob)

  avatar(formData)
}
`

2023-07-04 13:59 UTC, mironovsergey commented on packages/client/src/hooks/useErrors.ts
> +} => {
Есть ли смысл явно указывать тип возвращаемого значения

2023-07-04 14:00 UTC, mironovsergey commented on packages/client/src/pages/profile/components/profile-data/ProfileData.tsx
> +export const ProfileData = ({ user }: ProfileDataProps) => {
Лучше типизировать следующим образом, чтобы поддерживать единообразие с остальными компонентами
```
export const ProfileData: FC<ProfileDataProps> = ({ user }) 
```

2023-07-04 14:02 UTC, mironovsergey commented on packages/client/src/shared/helpers/errors.ts
> +import { AxiosError, AxiosResponse } from 'axios'
Лучше импортировать тип
```
import type { AxiosError, AxiosResponse } from 'axios'
```

2023-07-04 14:06 UTC, mironovsergey approved these changes
Описал несколько мелких недочетов

2023-07-04 15:26 UTC, dksr requested changes

2023-07-04 15:26 UTC, dksr commented on packages/client/package.json
> +    "axios": "^1.4.0",
зафиксируй версии

2023-07-04 15:26 UTC, dksr commented on packages/client/src/app/api/QueryClientProvider.tsx
> +import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
неиспользуемый импорт

2023-07-04 15:30 UTC, HelenaSuslenkova commented on packages/client/package.json
> +    "axios": "^1.4.0",
ты смотришь старую версию файла

2023-07-04 15:31 UTC, HelenaSuslenkova commented on packages/client/src/app/api/QueryClientProvider.tsx
> +import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
он используемый, я тестировала  query devtool, возможно кто-то так же захочет

2023-07-04 15:45 UTC, HelenaSuslenkova commented on packages/client/src/app/api/axios.ts
> +const API_BASE_URL = `https://ya-praktikum.tech/api`
в данном случае и те и другие выды кавычек работают одинаково

2023-07-04 15:45 UTC, HelenaSuslenkova commented on packages/client/src/app/api/axios.ts
> +  response => {
думаю это избыточно

2023-07-04 15:49 UTC, HelenaSuslenkova commented on packages/client/src/app/api/request.ts
> +  const onSuccess = function S(response: AxiosResponse) {
здесь уже указан тип возвращаемого значения `Promise<T>`

2023-07-04 15:50 UTC, HelenaSuslenkova commented on packages/client/src/hooks/useErrors.ts
> +} => {
да, мы типизируем функцию

2023-07-04 15:51 UTC, HelenaSuslenkova commented on packages/client/src/shared/helpers/errors.ts
> +import { AxiosError, AxiosResponse } from 'axios'
оба стиля написания работают одинаково

2023-07-04 16:11 UTC, dksr approved these changes

2023-07-05 06:08 UTC, Olegas commented on packages/client/src/app/api/QueryClientProvider.tsx
> +import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
Если в итоге этот код не используется, то его надо убрать. И импорт и закомментированный участок ниже

2023-07-05 06:09 UTC, Olegas commented on packages/client/src/app/api/axios.ts
> +const API_BASE_URL = `https://ya-praktikum.tech/api`
Согласен с замечанием. Верно, и те и другие виды кавычек работают одинаково. Но у использованных кавычек есть четкая задача - они нужны тогда, когда нужно подставить в строку какие-то переменные. Здесь этого нет. А значит надо использовать обычные кавычки. А раз в проекте для строк приняты одинарные - должны быть одинарные. Иначе в коде будет бардак.

2023-07-05 06:12 UTC, Olegas commented on packages/client/src/app/api/services/user.service.ts
> +const UploadFileHeaders = {
Совет: я бы назвал эту переменную с маленькой буквы. С большой обычно называют классы или типы. Здесь это просто константа.

2023-07-05 06:25 UTC, Olegas commented on packages/client/src/shared/helpers/errors.ts
> +import { AxiosError, AxiosResponse } from 'axios'
На самом деле замечание не лишено смысла. Хоть обе конструкции и работают одинаково в данном случае, импорт типа вместо импорта класса может иногда оградить от некоторых проблемы типа циклических зависимостей.

2023-07-05 06:34 UTC, Olegas requested changes
Требуется доработка
1. Есть замечания по коду, в том числе от коллег по команде, которые стоит исправить
2. Я нашел реализацию API для смены пароля но не нашел где она внедрена. По бэклогу в этой задаче должна быть смена аватара (есть) и смена пароля (не нашел)

2023-07-05 12:17 UTC, aaa15test approved these changes

2023-07-05 17:16 UTC, Olegas approved these changes

2023-07-05 17:33 UTC, merged