[CHE-16] Auth Logic
27-mf-05/cheburland pull request #30
Opened 2023-07-10 13:21 UTC by dksr

-Добавлен сервис Auth для API
-Добавлен контекст авторизации
-Добавлена логика авторизации и проверки на странице /login
-Сделаны редиректы на соответствующие страницы для авторизованного/неавторизованного пользователя

2023-07-10 14:09 UTC, mironovsergey approved these changes

2023-07-10 14:09 UTC, mironovsergey commented on packages/client/src/app/api/services/auth.service.ts
> +    })
Можно еще сюда добавить тип:
```
return request<{ id: number }>({
  url: AUTH_SIGNUP_PATH,
  method: 'post',
  data,
})
```

2023-07-10 14:09 UTC, mironovsergey commented on packages/client/src/app/api/services/auth.service.ts
> +window.AuthService = AuthService
Это здесь зачем?

2023-07-10 14:19 UTC, dksr commented on packages/client/src/app/api/services/auth.service.ts
> +window.AuthService = AuthService
> Это здесь зачем?

для дебага, чтобы можно было разлогиниться из консоли, потом уберем

2023-07-11 14:58 UTC, HelenaSuslenkova requested changes

2023-07-11 14:58 UTC, HelenaSuslenkova commented on packages/client/src/shared/types/auth.ts
> +}
Так как у нас есть уже тип User, то можно написать тип как-то так:
`type Auth = Omit<User, 'display_name | avatar | id'> & {password: string}
`

2023-07-11 14:58 UTC, HelenaSuslenkova commented on packages/client/src/app/api/services/auth.service.ts
> +window.AuthService = AuthService
лучше чтобы такие вещи в `develop` не попадали, нужно не забывать удалять

2023-07-11 14:58 UTC, HelenaSuslenkova commented on packages/client/src/pages/login/Login.tsx
> +
эту логику лучше вынести в хук, например с названием `useLogin`

2023-07-11 14:58 UTC, HelenaSuslenkova commented on packages/client/src/pages/login/Login.tsx
>            />
Круто было бы немного отрефакторить Login page component:
 вынести в отдельный компонент форму логина

2023-07-11 14:58 UTC, HelenaSuslenkova commented on packages/client/src/pages/login/Login.tsx
> +      form.setFieldError('password', 'Неверный логин или пароль')
В нашем проекте есть хук `useErrors`, там нужно обрабатывать ошибки сервера на уровне приложения.

2023-07-11 14:58 UTC, HelenaSuslenkova commented on packages/client/src/app/context/AuthContextProvider/AuthContextProvider.tsx
Если назвать `Session` или `Auth`, думаю будет более лаконично и понятно.  Но это на усмотрение, дело вкуса.

2023-07-11 14:58 UTC, HelenaSuslenkova commented on packages/client/src/app/api/axios.ts
Не добавлена логика регистрации, а без нее авторизацию новому пользователю не пройти

2023-07-11 14:58 UTC, HelenaSuslenkova commented on packages/client/src/pages/login/Login.tsx
Замени, пожалуйста, в рамках этой задачи на форме логина  инпут для пароля с `TextInput` на `PasswordInput`

2023-07-11 14:58 UTC, HelenaSuslenkova commented on packages/client/src/app/context/AuthContextProvider/AuthContextProvider.tsx
> +    fetchUser()
Даже если пользователь не авторизован - будет идти запрос на бек. Это нужно исправить

Кстати, есть задача https://linear.app/cheburland/issue/CHE-36/avtorizaciya-dolzhna-proveryatsya-cherez-otdelno-napisannyj-hook-ili . Можно совместить, "убив 3 зайца"
Реализовав HOC компонент для авторизации мы сможем убрать запрос на getUser для неавторизрванного пользователя, т. е. гибко управлять рендером компонентов, предназначенных для авторизованных и не для авторизованных пользователей

2023-07-11 16:05 UTC, dksr commented on packages/client/src/shared/types/auth.ts
> +}
> Так как у нас есть уже тип User, то можно написать тип как-то так: `type Auth = Omit<User, 'display_name | avatar | id'> & {password: string} `

я об этом подумал, только совсем некрасиво так выглядит тип. В первом модуле Егор Бережной именно так сделал, отдельно тип User, отдельно SignupData

2023-07-11 16:10 UTC, dksr commented on packages/client/src/app/api/services/auth.service.ts
> +window.AuthService = AuthService
> лучше чтобы такие вещи в `develop` не попадали, нужно не забывать удалять

убрал

2023-07-11 16:12 UTC, dksr commented on packages/client/src/pages/login/Login.tsx
> +
> эту логику лучше вынести в хук, например с названием `useLogin`

у меня как раз задача во втором спринте - сделать хук для авторизации. Иначе нечего будет в рамках нее делать.

2023-07-11 16:15 UTC, dksr commented on packages/client/src/pages/login/Login.tsx
>            />
> Круто было бы немного отрефакторить Login page component: вынести в отдельный компонент форму логина

тогда и в регистрации надо вынести, сделаем потом отдельную задачу по рефакторингу форм

2023-07-11 16:19 UTC, dksr commented on packages/client/src/app/api/axios.ts
> Не добавлена логика регистрации, а без нее авторизацию новому пользователю не пройти

отдельная задача, создай и дай мне ее

2023-07-11 16:31 UTC, HelenaSuslenkova commented on packages/client/src/pages/login/Login.tsx
> +
В задаче про другой хук речь идет
useLogin - должен содержать логику запроса к серверу на login
А в задаче говорится, что нужно создать хук или HOC компонент с логикой авторизации

2023-07-11 18:49 UTC, dksr commented on packages/client/src/pages/login/Login.tsx
> +      form.setFieldError('password', 'Неверный логин или пароль')
> В нашем проекте есть хук `useErrors`, там нужно обрабатывать ошибки сервера на уровне приложения.

сделал, подключил tostify для вывода ошибок и других информационных окон

2023-07-11 20:38 UTC, dksr commented on packages/client/src/pages/login/Login.tsx
> +
готово

2023-07-11 21:32 UTC, mironovsergey commented on packages/client/src/shared/types/auth.ts
> +}
Я тоже, во время первого модуля, подумывал над тем, что было бы хорошо определить отдельно по два типа (Request и Response) для каждого эндпоинта, и именовать их по определенным правилам. Например, для получения данных пользователя можно создать типы UserRequest и UserResponse. Даже если у нас определен тип User, используемый в ui-компонентах, полностью идентичен типу UserRequest или UserResponse,  не следует его использовать в запросах. Да, в каких-то случаях мы получим дублирование кода. Но плюсов, по-моему, больше:
* Имея хорошую документацию по API, мы можем заранее определить типы запросов и ответов, до написания ui-компонентов.
* Строгие правила именования типов.
* Обеспечиваем единообразие кода.
* Улучшаем читаемость кода.
* Исключаем ошибки в случае изменения (добавлени/удаление) полей типов.

2023-07-11 21:47 UTC, HelenaSuslenkova approved these changes

2023-07-11 22:26 UTC, merged