[CHE 34] Add game visual part
27-mf-05/cheburland pull request #35
Opened 2023-07-15 06:51 UTC by aaa15test

Доработана визуальная часть игры

<img width="1312" alt="Снимок экрана 2023-07-15 в 09 44 46" src="https://github.com/27-mf-05/cheburland/assets/91631529/0b3354bb-4001-4290-990c-b45cc1bd11e4">

2023-07-15 11:08 UTC, GeorgyPasyuk requested changes

2023-07-15 11:08 UTC, GeorgyPasyuk commented on packages/client/src/core/hero/Hero.tsx
> +const beigeСolor = 'rgb(202, 132, 69)'
Тут кажется в beigeColor, буква C - написана кириллицей

2023-07-15 11:08 UTC, GeorgyPasyuk commented on packages/client/src/core/oranges/Oranges.tsx
> +      render(ctx)
Тут скорее всего ты имела ввиду this._context

2023-07-15 11:08 UTC, GeorgyPasyuk commented on packages/client/src/core/oranges/Oranges.tsx
>  }
Еще у меня небольшой баг, что не всегда появляются частицы

2023-07-15 14:54 UTC, dksr commented on packages/client/src/core/hero/Hero.tsx
>      context.closePath()
Чебурашка будет статическим? Может сделать движение ног хотя бы?

2023-07-15 14:54 UTC, dksr reviewed
Чебурашка будет статическим? Может сделать движение ног хотя бы?

2023-07-15 15:28 UTC, aaa15test commented
@dksr На данный момент чебурашка статический, есть анимация только на исчезание апельсина. Позже я могу доработать этот момент и добавить анимацию для чебурашки

2023-07-15 16:12 UTC, dksr approved these changes

2023-07-15 17:42 UTC, GeorgyPasyuk approved these changes

2023-07-16 11:41 UTC, Olegas requested changes
Добрый день.
Есть замечания по организации кода, написал комментарии

2023-07-16 11:41 UTC, Olegas commented on packages/client/src/core/oranges/Oranges.tsx
> +    const angleTools = {
angleTools явно стоит вынести в библиотеку отдельную. Аналогично я бы вынес хелпер Particle - не надо постоянно определять новые экземпляры функций.

2023-07-16 11:41 UTC, Olegas commented on packages/client/src/core/oranges/Oranges.tsx
> +    }
Эту функцию бы тоже вынести и не определять постоянно

2023-07-16 11:41 UTC, Olegas commented on packages/client/src/core/oranges/Oranges.tsx
> +    function random(a: number, b: number) {
Еще одна библиотечная функция

2023-07-16 11:41 UTC, Olegas commented on packages/client/src/core/oranges/Oranges.tsx
> +      if (ctx !== null) render(ctx)
А как остановить эту бесконечную анимацию?

2023-07-16 17:35 UTC, Olegas approved these changes

2023-07-17 06:30 UTC, merged