[CHE -35] Add service worker
27-mf-05/cheburland pull request #36
Opened 2023-07-15 15:19 UTC by HelenaSuslenkova

-Добавила service worker со стратегией "Network first, falling back to cache"

2023-07-15 16:38 UTC, dksr requested changes

2023-07-15 16:38 UTC, dksr commented on packages/client/service-worker.js
> +const CACHE_VERSION = 'v1'
версионирование не должно быть статическим. Можно добавить хеш файлов в версию, чтобы при их изменении кеш обновлялся автоматически

2023-07-15 16:38 UTC, dksr commented on packages/client/src/AppServiceWorker.ts
> +    if ('serviceWorker' in navigator) {
Дублируется проверка, можно перенести в конструктор

2023-07-15 16:38 UTC, dksr commented on packages/client/src/AppServiceWorker.ts
> +          console.error(error.message)
все ошибки нужно обрабатывать в useError

2023-07-15 16:38 UTC, dksr commented on packages/client/service-worker.js
> +}
Почему этот файл без типизации?

2023-07-15 19:00 UTC, dksr approved these changes

2023-07-16 09:37 UTC, Olegas approved these changes
Принято

2023-07-16 13:20 UTC, merged