[CHE-37] Add full screen api
27-mf-05/cheburland pull request #50
Opened 2023-07-24 19:24 UTC by HelenaSuslenkova

-add fullscreen api for Game component
-minor refactoring GameBoard

2023-07-24 20:31 UTC, GeorgyPasyuk approved these changes

2023-07-24 21:10 UTC, dksr approved these changes

2023-07-24 21:10 UTC, dksr commented on packages/client/src/hooks/useFullScreen.ts
> +      // @ts-ignore
Чтобы не писать игноры и не вызывать ошибки eslint, можно кастануть тип один раз на строке 9:
const d = document as any

2023-07-24 23:09 UTC, mironovsergey requested changes
На странице Game проблемы с версткой. Если высота окна меньше содержимого страницы, то контент оказывается за пределами верхней части страницы. Нижняя часть содержимого, при этом, оказывается, не заполнена бэкграундом.

2023-07-24 23:09 UTC, mironovsergey commented on packages/client/src/core/scene/Scene.tsx
> +export const Scene: FC<GameProps> = ({
Переименование компонента игры `Game` в` Scene`. Я немного знаком с библиотекой `Phaser` для создания 2D-игр. Сцена является частью игры. Игра в один момент может содержать несколько сцен, например: игровое поле и мини-кара. Поэтому подобное переименование не считаю удачным.

2023-07-24 23:09 UTC, mironovsergey commented on packages/client/src/pages/game/Game.tsx
> +      children: <GameStart start={handleStartGame} />,
Переименование пропса `onCountdownEnd` в `start`. Наименование `start` не является информативным и не отражает сути происходящего, в то время как `onCountdownEnd` - указывает, что данное событие наступает в момент окончания обратного отсчета, и может выполнять все, что угодно.

2023-07-24 23:09 UTC, mironovsergey commented on packages/client/src/pages/game/Game.tsx
> +      innerProps: { startGame: handleModalStart },
Переименование пропса `onOpenGameStartModal` в `startGame`. Этот обработчик события не стартует сам по себе игру, но открывает модальное окно.

2023-07-24 23:09 UTC, mironovsergey commented on packages/client/src/pages/game/Game.tsx
> +  const handleCollision = useCallback(() => {
Переименование обработчика `handleIncreaseScore` в `handleCollision`. Компонент страницы игры не должен знать, при какой механике игры увеличивается счет очков. В перспективе очки могут увеличиваться не только при пересечении игрового персонажа и объекта для сбора.

2023-07-24 23:09 UTC, mironovsergey commented on packages/client/src/pages/game/Game.tsx
> +      <GameInfo handleModalStart={handleModalStart} />
Переименование пропса `onOpenGameStartModal` в `handleModalStart`. В документации `react` указаны общепринятые правила именования хендлеров и пропсов, по средствам которых выполняется передача вниз по иерархии компонентов.  Хендлеры обычно именуются с префиксом `handle`, за которым следует описание события, например: `handleClick`, `handleSubmit`, и т.д. Пропсы, в которых передаются хендлеры, именуются с префиксом `on`, например: `onClick`, `onSubmit`, и т.д. По подобию атрибутов html-тегов.

2023-07-24 23:09 UTC, mironovsergey commented on packages/client/src/pages/game/Game.tsx
> +  const handleModalStart = useCallback(() => {
Переименование обработчика `handleOpenGameStartModal` в `handleModalStar`t. На мой взгляд, наименование `handleModalStart` не является описательным и информативным, так как не отражает какое именно модальное окно должно открыться. В этом компоненте может быть несколько модальных окон. А если часть наименования ModalStart указывает на модальное окно старта игры, то не отвечает на вопрос, что он делает.

2023-07-24 23:09 UTC, mironovsergey commented on packages/client/src/pages/game/components/game-board/GameBoard.tsx
> +)
Непонятна надобность компонента `GameBoard`.

2023-07-25 10:18 UTC, HelenaSuslenkova commented on packages/client/src/pages/game/components/game-board/GameBoard.tsx
> +)
Это врапер для игры. В дальнейшем его надобность будет более понятна, когда мы прикрутим дополнительный функционал  (компонент отсчета времени игры и тд)

2023-07-25 20:24 UTC, mironovsergey approved these changes

2023-07-25 22:44 UTC, mironovsergey requested changes
Критические замечания должны быть исправлены в том PR, в котором они допущены, прежде чем заливать в develop.

2023-07-26 15:03 UTC, HelenaSuslenkova commented
> Критические замечания должны быть исправлены в том PR, в котором они допущены, прежде чем заливать в develop.

На верстку Main page есть отдельная задача

2023-07-26 17:07 UTC, merged