[CHE 48] added Notification api
27-mf-05/cheburland pull request #53
Opened 2023-07-31 21:43 UTC by GeorgyPasyuk

Добавлен Notification api
TODO: 
Взаимодействие с игровым рекордом

2023-08-01 07:50 UTC, aaa15test approved these changes

2023-08-01 09:16 UTC, HelenaSuslenkova approved these changes

2023-08-01 22:28 UTC, dksr approved these changes

2023-08-02 06:03 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду - написал подробно в комментариях.
Нужно доработать.

2023-08-02 06:03 UTC, Olegas commented on packages/client/src/hooks/useNotificationApi.ts
> +          alert('Пожалуйста, разрешите уведомления')
Не уверен что это хорошая практика - спамить пользователя алертами (которые блокируют окно) если он явно отключил уведомления. Я бы не стал таким приложением пользоваться.

2023-08-02 06:03 UTC, Olegas commented on packages/client/src/hooks/useNotificationApi.ts
> +    alert('Уведомления не поддерживаются')
И вот тут та же история - ну не поддерживаются, и что? Зачем мне об этом каждый раз сообщать? Если это нужно сделать для отладки - лучше вывести что-то в консоль тогда

2023-08-02 06:03 UTC, Olegas commented on packages/client/src/hooks/useNotificationApi.ts
> +          alert('Пожалуйста, разрешите уведомления')
А вот это уже можно показать, но лучше опять же не алертом, который все блокирует, а какой-то аккуратной подсказкой в углу экрана например - "смотрите, у нас есть уведомления, их можно разрешить". Наверняка видел такие сообщения на разных сайтах. Но тут совет - это не блокирует приемку работы.

2023-08-02 06:03 UTC, Olegas commented on packages/client/src/hooks/useNotificationApi.ts
> +  if ('Notification' in window) {
Тут есть проблема.
Размещение уведомления происходит каждый раз при обращении к хуку. Представь что у тебя родительский компонент, там где ты этот хук внедряешь, перерисовался по какой-то причине несколько раз. Каждый раз будет показано новое уведомление.
Думаю здесь надо смотреть на score и если оно не поменялось - то ничего не показывать, тут поможет useEffect с нужной зависимостью.

2023-08-04 06:30 UTC, Olegas requested changes
Стало лучше, но в то же время и сложнее.

Много логики работы с напоминаниями "протекло" в приложение.
Зачем вам slice с признаком, включена нотификация или нет? 
Изначальная задумка с единственным методом notifyUser была правильная. Надо продолжить ее развивать. Давай инкапсулируем запрос прав и хранение статуса запроса внутри hook (у тебя для этого есть уже там useState)

Пусть у hook будет такое API: одна единственная функция notifyUser. Дальше, когда запрошен показ уведомления, запросим разрешение на показ. Если есть - просто покажем, если пользователь не принял решение - покажем toast, если запрет - просто ничего не сделаем. Это все можно инкапсулировать внутри хука, без хранения в редаксе, без дополнительного компонента.

Признак, что пользователь закрыл toast, можно так же как у тебя сейчас сделано - хранить в localStorage.

2023-08-06 07:50 UTC, Olegas approved these changes
Отлично! Работа принята

2023-08-06 12:10 UTC, merged