[CHE-47] Leaderboard api add
27-mf-05/cheburland pull request #56
Opened 2023-08-06 12:45 UTC by aaa15test

Добавлено Leaderboard api

<img width="973" alt="Снимок экрана 2023-08-06 в 15 17 00" src="https://github.com/27-mf-05/cheburland/assets/91631529/856607ff-ac24-40b5-b307-a8d315eddd98">

2023-08-06 20:43 UTC, dksr approved these changes
<img width="1142" alt="image" src="https://github.com/27-mf-05/cheburland/assets/61501278/cf526b9b-d046-4bed-852e-5aec9b7789c1">
Множество предупреждений eslint, надо или сделать то что он говорит, либо заигнорить

2023-08-08 21:56 UTC, IvanPeleshok commented on packages/client/src/app/redux/api/leaderboard.api.ts
> +export const { useAddUserToLeaderboardMutation, useAllLeaderboardQuery } =
Подобные конструкции предлагаю оформлять следующим образом
```
export const {
 var1,
 va2
} = var3
```

2023-08-08 21:59 UTC, IvanPeleshok commented on packages/client/src/hooks/useLeaderboard.ts
> +      const result = data.map((item, i) => {
Предлагаю не сокращать (index)

2023-08-08 22:03 UTC, IvanPeleshok commented on packages/client/src/pages/leader-board/LeaderBoard.tsx
> +    const leaderboard: any = await handleGetAllLeaderboard()
Необходимо указать тип, any не пойдёт

2023-08-08 22:05 UTC, IvanPeleshok commented on packages/client/src/pages/game/Game.tsx
> +    } else if (gameStatus === GameStatus.Finished) {
else if избыточно, т.к в if есть return
```
if () {
  ...
  return
}

if () {
  ...
  return
}
```
Таким образом, код остаётся плоским

2023-08-08 22:07 UTC, IvanPeleshok requested changes
Хорошая работа, но есть небольшие замечания

2023-08-09 08:49 UTC, aaa15test commented on packages/client/src/app/redux/api/leaderboard.api.ts
> +export const { useAddUserToLeaderboardMutation, useAllLeaderboardQuery } =
исправила оформление конструкции в соответсвии с примером, но после комита все снова возвращается в прежний вид

2023-08-09 10:39 UTC, IvanPeleshok approved these changes

2023-08-09 10:44 UTC, merged