Che 61.theme switching client
27-mf-05/cheburland pull request #60
Opened 2023-08-14 12:00 UTC by ThunderbirdSecret

-Переключение темы, клиент
-добавлен компонент переключатель темы "ThemeSwitch"
-добавлена темная тема в themeDark

2023-08-14 13:05 UTC, HelenaSuslenkova requested changes
- Title пр-ов нужно оформить в таком формате: `[CHE-61] Theme switching client ` (см. документацию)

 -  На главной странице, если переключить на темную тему,  кнопки в меню перестают быть четко видны, нужно сделать их более четкими по цвету

2023-08-14 13:05 UTC, HelenaSuslenkova commented on packages/client/src/app/App.tsx
> +  }, [colorScheme])
Лучше эту логику вынести в отдельный кастомный хук, назвать его, например, `useTheme`

2023-08-14 13:05 UTC, HelenaSuslenkova commented on packages/client/src/app/theme/theme.ts
В `dark` и `light` темах некоторые атрибуты общие. есть смысл вынести их в отдельный объект темы. А в `themeLight` и `themeDark` оставить только цветовые настройки

2023-08-14 14:09 UTC, dksr requested changes
Баг, у кнопок пропал background
<img width="1181" alt="image" src="https://github.com/27-mf-05/cheburland/assets/61501278/dc083c99-1e19-4007-9d27-86de9373648f">

2023-08-14 14:16 UTC, dksr reviewed
Сама темная тема и переключатель выглядят хорошо, молодец

2023-08-14 14:16 UTC, dksr commented on packages/client/jest.config.js
> +    '\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
Лучше не добавлять в pr файлы, которые не относятся к задаче, тем более если они были изменены prettier

2023-08-14 14:33 UTC, GeorgyPasyuk requested changes
Не срабатывает hover в тёмной теме на главной странице
<img width="776" alt="image" src="https://github.com/27-mf-05/cheburland/assets/115622303/18fe9662-da1b-4071-8c24-628b7aa1556a">

2023-08-17 14:28 UTC, HelenaSuslenkova requested changes

2023-08-17 14:28 UTC, HelenaSuslenkova commented on packages/client/src/hooks/useTheme.tsx
> +export const useTheme = () => {
Есть смысл протипизировать возвращаемый `useTheme` объект

2023-08-17 14:28 UTC, HelenaSuslenkova commented on packages/client/src/app/App.tsx
> +  // }, [colorScheme])
комментарии нужно удалить, чтобы не засорять код

2023-08-17 14:36 UTC, ThunderbirdSecret commented on packages/client/src/app/App.tsx
> +  // }, [colorScheme])
Смотри последние коммиты, этот уже не актуален )

2023-08-17 14:46 UTC, ThunderbirdSecret commented on packages/client/src/hooks/useTheme.tsx
> +export const useTheme = () => {
готово

2023-08-17 22:35 UTC, dksr approved these changes

2023-08-17 23:59 UTC, closed without merging