[CHE 64] Forum api
27-mf-05/cheburland pull request #68
Opened 2023-08-20 11:56 UTC by GeorgyPasyuk

Созданы апи для форума, база данных, модели, контроллеры.

Чтобы протестировать работу запустите команду docker compose up

Далее перейдите в postman, где можно ввести следующие JSON запросы:

POST http://localhost:3000/topic - body :
{
"title": "1",
"replies_count": 1,
"message": "1"
}
Создает соответствующий полю body топик;

POST http://localhost:3000/topic/:topicId/comment
Вместо topicId введите id созданного топика (get по url топика), либо 1 - т.к. id генерируются для всех сущностей последовательно.
body:
{
"author_name": "1",
"message": "1"
}
Создает соответствующий полю body комментарий;

POST http://localhost:3000/topic/:topicId/comment/commentId/reply - body :
{
"author_name": "1",
"message": "1"
}
Создает соответствующий полю body ответ на комментарий;

Также можете проверить базу данных через pgAdmin

Важно отметить структуру базы данных:

Topic --> Comment --> Reply

У топика может быть много комментариев, у комментария может быть много ответов, но не наоборот.

Поэтому запрос по несуществующему Id родительской сущности приведет к ошибке.

Чтобы просмотреть список всех доступных запросов перейдите в папку:
packages/server/orm/routes/*Routes/*Routes.ts
Где находятся роуты для запросов каждой сущности.

На данный момент нельзя смерджить PR, т.к. рефакторинг проекта проходил параллельно выполнению этой задачи, поэтому в дальнейшем будет проводиться общий рефакторинг.

2023-08-20 16:37 UTC, ThunderbirdSecret approved these changes
Проверено в postman все ссылки рабочие. Отлично выполненная работа, замечаний нет

2023-08-20 17:11 UTC, Olegas requested changes
Добрый день.
Есть вопросы по организации API
Написал комментарии к коду.

2023-08-20 17:11 UTC, Olegas commented on packages/server/orm/controllers/CommentController/CommentController.ts
> +      author_name,
А у вас в проекте еще нет мидлвары, которая выполняет авторизацию запросов? Данные о пользователе бы лучше оттуда брать, а не давать вводить самому пользователю

2023-08-20 17:11 UTC, Olegas commented on packages/server/package.json
> +    "pg-hstore": "^2.3.4",
Для чего вам hstore? Не увидел его использования в коде

2023-08-20 17:11 UTC, Olegas commented on packages/server/db.ts
> +      host: 'postgres',
Для вот этого бы лучше переменную окружения использовать. Что бы можно было запускать и локально и в докере

2023-08-20 17:11 UTC, Olegas commented on packages/server/orm/controllers/ReplyController/ReplyController.ts
> +  static async getReplies(_req: Request, res: Response) {
Для чего такой метод? Зачем может понадобиться получить вообще все реплаи? Обычно же я хочу посмотреть реплаи для конкретного коммента.

2023-08-20 17:11 UTC, Olegas commented on packages/server/orm/controllers/CommentController/CommentController.ts
> +    const data = await CommentModel.findAll()
Такой же вопрос как к реплаям. Для чего получать все комментарии? Обычно мы видими комментарии для конкретного топика

2023-08-21 06:56 UTC, KletskovG commented on packages/client/package.json
> +    "pg": "^8.11.2",
Все версии пакетов всегда стоит фиксировать

2023-08-21 06:56 UTC, KletskovG commented on packages/server/orm/controllers/TopicController/TopicController.ts
> +  static async getTopics(_req: Request, res: Response) {
В идеале тут нужно было сделать какой-то лимит или пагинацию - если в бд будет тысяча топиков и тут они будут выкачиваться из базы и отправляться - будет проблема, но конкретно сейчас это добавлять не обязательно

2023-08-21 06:56 UTC, KletskovG commented on packages/server/orm/controllers/TopicController/TopicController.ts
> +    res.json('success')
Обычно в таких запросах в качестве ответа можно отправить id удаленного объекта, эта инфа может быть полезна на фронте

2023-08-21 06:56 UTC, KletskovG commented on packages/server/orm/index.ts
> +  associations
Какая-то странная запись.
Ты ничего не экспортируешь из associations, соответственно, тут не можешь это вызывать. В целом эта строка в рамках синтаксиса js ничего не сделает

Если ты хотел просто запустить код для связей в бд, то код в associations можно завернуть в функцию, ее как раз экспортировать, тут импортировать и вызывать

2023-08-21 19:06 UTC, Olegas commented on packages/server/orm/controllers/ReplyController/ReplyController.ts
> +    res.json(`updated reply ${id}`)
Думаю в замечании про возврат идентификатора речь была о том, что бы вернуть его "как есть" а не в составе строки. С ответом от API обычно работает код, а не человек, тут не надо писать словами что-то, тут лучше вернуть "машино-читаемый" ответ.

2023-08-21 19:06 UTC, Olegas commented on packages/server/orm/controllers/TopicController/TopicController.ts
> +  static async getTopics(_req: Request, res: Response) {
Кстати да, очень правильное замечание. Полностью согласен.

2023-08-21 19:08 UTC, Olegas commented on packages/server/orm/controllers/ReplyController/ReplyController.ts
> +    const data = await ReplyModel.findAll({ where: { commentId } })
Если появился поиск по id комментария и топика, нужно добавить индексы на соответствующие поля

2023-08-21 19:09 UTC, Olegas requested changes
1. Нет ответа про мидлвару авторизации.
2. Раз появился поиск по связанной сущности, нужно добавить индексы (написал отдельный комментарий)
3. Справедливое замечание от коллеги по команде про пагинацию в списке топиков

2023-08-21 20:25 UTC, HelenaSuslenkova commented
Middleware c авторизацией у нас пока нет, сделаем в дальнейшем

2023-08-24 16:14 UTC, GeorgyPasyuk commented
> 1. Нет ответа про мидлвару авторизации.
> 2. Раз появился поиск по связанной сущности, нужно добавить индексы (написал отдельный комментарий)
> 3. Справедливое замечание от коллеги по команде про пагинацию в списке топиков

Далее в проект будет внедрена middleware для использования данных пользователя в запросах (чтобы не вводить вручную имя автора комментария или ответа), сейчас у нас её нет, но мы обязательно исправим эту часть.

2023-08-25 08:01 UTC, Olegas approved these changes
Работа принята

2023-09-07 08:46 UTC, closed without merging